# Generated by Django 5.1.7 on 2025-03-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('hours', models.IntegerField()),
                ('track', models.ManyToManyField(related_name='courses', to='track.track')),
            ],
        ),
    ]
